<a href="https://colab.research.google.com/github/anakhashibu1999/ML-projects/blob/main/PCA(iris).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv('/content/Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
X=df.iloc[:,1:5]
y=df.iloc[:,-1]

In [ ]:
X

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [ ]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [ ]:
from sklearn.decomposition import PCA
pca=PCA(n_components=1)
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)

In [ ]:
X_train

array([[ 3.28839601e+00],
       [-1.78693817e+00],
       [-2.29903611e+00],
       [-2.03678920e+00],
       [-3.53870902e-04],
       [-2.09669207e+00],
       [-1.96032351e+00],
       [ 2.51578601e+00],
       [ 1.87500168e+00],
       [ 2.31370144e+00],
       [ 1.85328732e+00],
       [ 1.17153320e+00],
       [ 4.82785375e-01],
       [ 2.89868807e+00],
       [ 1.13182256e-01],
       [-2.25505246e+00],
       [ 1.22255537e+00],
       [ 1.32103972e+00],
       [-2.18226227e+00],
       [-2.31186977e+00],
       [ 1.87719297e+00],
       [-2.37565395e+00],
       [ 1.03501248e+00],
       [ 1.39566325e+00],
       [ 9.09214631e-01],
       [ 3.90328797e-01],
       [ 2.03149307e+00],
       [ 9.38343473e-01],
       [-2.27513046e+00],
       [ 5.15858013e-01],
       [ 7.17969411e-01],
       [ 1.48751185e+00],
       [-4.04934622e-01],
       [ 1.87519865e+00],
       [ 2.56768330e-01],
       [-2.06393256e+00],
       [-2.13843077e+00],
       [-2.47553384e+00],
       [ 1.74054693e+00],
       [-2.39746679e+00],
       [ 1.05011792e+00],
       [ 1.58918025e+00],
       [ 9.73321106e-01],
       [-2.08577223e+00],
       [-1.75982164e+00],
       [ 1.57067414e-01],
       [-2.13843077e+00],
       [ 2.43720952e+00],
       [ 5.90454712e-01],
       [ 2.76908057e+00],
       [ 1.87997423e+00],
       [ 1.00414880e+00],
       [ 1.41566076e+00],
       [ 2.32341392e+00],
       [-2.24710125e-02],
       [-2.09705003e+00],
       [ 2.36717160e-01],
       [-1.89111032e+00],
       [ 9.83094526e-02],
       [ 1.27402417e+00],
       [-1.98206469e+00],
       [ 1.26313116e+00],
       [-1.88942914e+00],
       [-2.15631748e+00],
       [ 1.61797796e+00],
       [ 9.67373827e-01],
       [ 2.06843818e+00],
       [-2.14052357e+00],
       [-2.10973154e+00],
       [ 7.68911099e-01],
       [-2.25696628e+00],
       [ 1.14081283e+00],
       [-2.09653992e+00],
       [ 1.53424993e+00],
       [ 3.29728671e-01],
       [-2.34271546e+00],
       [ 1.61593882e+00],
       [-2.59978400e+00],
       [ 8.92497796e-02],
       [-2.31171762e+00],
       [-7.33874200e-03],
       [-1.80598764e-01],
       [-2.18244124e+00],
       [-2.04576838e+00],
       [-5.21529484e-01],
       [-2.68571215e+00],
       [ 4.58906557e-01],
       [ 7.31080539e-01],
       [-2.16044942e+00],
       [ 1.08068615e+00],
       [ 2.38756302e-01],
       [ 1.17161369e+00],
       [ 1.14638415e+00],
       [ 1.14081283e+00],
       [-1.83959670e+00],
       [-1.91618771e+00],
       [ 1.18579802e+00],
       [ 4.80799892e-01],
       [ 1.88707521e+00],
       [-5.13223885e-02],
       [ 1.11581593e+00],
       [ 1.37091699e+00],
       [ 1.20850514e+00],
       [ 2.03151990e+00],
       [-2.13843077e+00]])

In [ ]:
pca.explained_variance_ratio_

array([0.71922887])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=25,criterion='entropy')
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
y_pred

array(['Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica'], dtype=object)

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9111111111111111